### ISSUE TITLE
Client-side pageviews

### ISSUE THREAD

**Issue by Saganic** [mitjans/nuxt-posthog#19]
Hi, it doesn't appear that the capturePageViews config property actually results in page views being tracked on client-side navigations using the router.beforeEach hook in posthog.client.ts

Any idea why this would be? I've tried both not setting the config in nuxt.config as well as explicitly setting the value to true. For our site, we appear to get intiial SSR loads tracking, but not client-side routes thereafter.

Thanks for your help

**Comment by mitjans** [comment]
Good catch, thanks! Should be fixed in the new release

**Comment by Saganic** [comment]
Confirm fixed and working in our prod env. Thank you for the quick fix
