### ISSUE TITLE
Enabled setting

### ISSUE THREAD

**Issue by jonatandorozco** [mitjans/nuxt-posthog#24]
This will help to disable the capturing the working on dev, thus avoiding sending false positives to posthog.

**Comment by mitjans** [comment]
I'm not quite sure I understand the problem at hand @jonatandorozco 
If you don't want to have false positives when you are in the development environment I suggest 2 things:
- Create a separate PostHog project inside your Organization for other environments. You can have projects for development/staging/production/etc.
- Disable PostHog during development if you don't need it

Let me know if this helps!

**Comment by jonatandorozco** [comment]
Thanks @mitjans, how can it be disabled?

**Comment by mitjans** [comment]
By removing the environment variables `POSTHOG_API_KEY` and `POSTHOG_API_HOST` it should stop sending events to PostHog.

**Comment by mitjans** [comment]
Sounds like a good idea! I'll give it some time this weekend.
Thank you for the suggestion ❤️

**Comment by jonatandorozco** [comment]
Thanks, @mitjans, if you need help with testing or something just let me know

And thank you for this package. Awesome work
