### ISSUE TITLE
Any option to disable until/unless enabled?

### ISSUE THREAD

**Issue by mohamnag** [mitjans/nuxt-posthog#32]
I'm looking for a way to prevent any kind of interaction with Posthog server until a certain criteria is met or it is explicitly activated. The major concern is related to GDPR and similar laws which might even make trouble if a first request is sent to server before user's consent is given (IP addresses are considered potentially personal identification data).

The flow I can think of is:
- in first visit of a user, he is shown the consent and depending on the scope user agrees to, this plugin is configured and activated
- user's preference is stored somewhere, until it is changed by user 
- in future visits user's preference is loaded and plugin is configured and activated accordingly (no consent pop up/message/... needed)

how is this doable using this extension?

**Comment by mitjans** [comment]
Hey @mohamnag!
Have you tried using [the config `disabled`](https://nuxt-posthog.cmitjans.dev/configuration)? I'm not sure it will cover all cases, but might be a good starting point to improve this flow.

**Comment by mohamnag** [comment]
@mitjans I saw that config, however it was/is not clear to me whether:
1. this also prevents any initial connection to Posthog (for sake of loading JS files, ...)
2. this can be changed on the fly in any later phase (like after page load or on user click, ...) and its change will take effect

could these be answered? would be nice to put them into the doc. 

We had a case where some lawyers took it on themselves to earn some money on websites that included analytics libraries and already made a first request to server for loading JS files before user decides on consent question.

**Comment by mitjans** [comment]
Maybe `disabled` is not the way to go, since as you mention it is not possible to modify at runtime.

After further investigation, I've seen that `posthog-js` has a configuration to [start in "opt-out mode" ](https://posthog.com/docs/libraries/js#opt-users-out).

I've played a bit with this option and looks like it should solve your problem. Here's a list of the steps I followed:

1. Modify your `nuxt.config.ts` file to start PostHog in opt-out mode:
	```typescript
	  posthog: {
	    clientOptions: {
	      opt_out_capturing_by_default: true,
	    },
		...
	  },
	```
2. In your cookies banner (or wherever you let your user opt-in), add the following code:
	```typescript
	const { $clientPosthog } = useNuxtApp();
	$clientPosthog?.opt_in_capturing();
	```

Let me know if this solves it for you!

**Comment by mohamnag** [comment]
hm thanks for investigation. this is very helpful. I will check this and come back. I would say this is a very important piece of information to potentially end up in the docs.

**Comment by toniengelhardt** [comment]
I'm getting warnings about missing API keys even if the extension is enabled. IMO this should not happen. 

Ideally the integration would just be disabled if the API keys are missing.

![Screenshot 2024-07-06 at 15 49 50](https://github.com/mitjans/nuxt-posthog/assets/2703233/103caadd-6816-4410-9049-8ebac5129cb4)

**Comment by toniengelhardt** [comment]
Thanks @mitjans 🙏🏽
