### ISSUE TITLE
No $pageleave events have been received

### ISSUE THREAD

**Issue by toniengelhardt** [mitjans/nuxt-posthog#35]
I'm seeing this warning in the PostHog UI:

<img width="1222" alt="Screenshot 2024-07-19 at 14 21 07" src="https://github.com/user-attachments/assets/b17f3485-62e9-44bc-8828-2bf52c258850">

According to the docs, the `capture_pageleave` setting should be turned on by default. 

<img width="685" alt="Screenshot 2024-07-19 at 14 27 18" src="https://github.com/user-attachments/assets/8f7bec8c-6a74-4156-b838-dc1cf956b1a5">

Is there anything I have to configure to make this work?

**Comment by mitjans** [comment]
Have you tried manually activating this feature through PostHog options?
In `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
  posthog: {
    clientOptions: {
      capture_pageleave: true,
    },
  },
});
```

I was able to receive page leave events with this setting turned on. By default this module setsa `page_view` to `false`, and maybe this affects somehow to `page_leave` as well (although I haven't seen the documentation mentioning it)

**Comment by toniengelhardt** [comment]
Thanks, I'll try that 🙏🏽
