### ISSUE TITLE
✨ Auto disabled in all env except production

### ISSUE THREAD

**Issue by jd-solanki** [mitjans/nuxt-posthog#36]
Hi 👋🏻 

Thanks for creating this module. I was checking docs and found that we've first disable the module in dev mode to accidently avoid tracking. Hence, I added below in nuxt config:
```ts
disabled: process.env.NODE_ENV !== 'production'
```

How about adding this to source code. I don't have that much experience with nuxt modules so just suggesting it.

**Comment by mitjans** [comment]
Could Nuxt [Environment overrides](https://nuxt.com/docs/getting-started/configuration#environment-overrides) fix this for you?

It makes sense to disable this module in all environments except for production, although I would do it under a specific setting.

**Comment by jd-solanki** [comment]
Thanks. Even if we use env overrides then we do have to specify the env for dev.

This is just my opinion if you don't think this brings anything useful to the table. Feel free to close the issue.

I just want to find out what is the proper way to handle prod & dev.
