### ISSUE TITLE
Can't capture custom events

### ISSUE THREAD

**Issue by jd-solanki** [mitjans/nuxt-posthog#37]
Hi 👋🏻 

Sorry for disturbing you. I love that you created this nuxt module. It's really nice.

I implemented it and can see everything on my posthog dashboard however there's two issue I'm facing:
1. There's type issue with my setup `nuxt-posthog@1.5.0`
  ![image](https://github.com/user-attachments/assets/3d9bdb82-a482-4aae-85ea-72da029f5cc6)
  ![image](https://github.com/user-attachments/assets/287eed2d-64d1-4440-88b2-fc260a9a3fbf)
2. Also my custom event I shown in second screenshot isn't get triggered or (this is silly) I don't know where to look for in posthog dashboard.

I checked your source code but it looks fine so creating this issue.

**Comment by mitjans** [comment]
Thank you for the support!

I haven't been able to reproduce this issue. Can you try running `npm run postinstall`? and make sure you have `nuxt-posthog` in your `modules` array inside `nuxt.config.ts` 😉 

I'll be releasing a new version now, can you try it again?

**Comment by jd-solanki** [comment]
With the new update everything is fine and event is captured!

Thanks man 🥂
