### ISSUE TITLE
Can't capture custom events using v-directive

### ISSUE THREAD

**Issue by IzakJackson** [mitjans/nuxt-posthog#53]
Hi,

I'm trying to capture custom events using the v-directive:

```
<UButton
          v-posthog-capture="'book_now_clicked'"
          size="xl"
          class="w-full cursor-pointer justify-center text-center"
        >
          Enquire Now
        </UButton>
```

No custom events are showing in my Posthog dashboard.

I'm using Nuxt ui3 for the button if that helps.

**Comment by mitjans** [comment]
I can't reproduce, can you provide more context?

**Comment by IzakJackson** [comment]
When clicking the button with the v-directive, the event isn't logged in my posthog dashboard. This happens for all uses of it throughout my app.

Page views, session replay etc. all work for me, just not v-posthog-capture.

Is there any additional setup to use v-posthog-capture? My assumption is that if posthog is setup on the project I can use the v-diredctive without importing into the component, or is importing required?

**Comment by IzakJackson** [comment]
I think it might be.

`<UButton>` has a root of `<ULink>`, which has a root of `<NuxtLink>`.

Using just `<NuxtLink>` logs my custom events.

**Comment by IzakJackson** [comment]
Nuxt ui3 is based on radix-vue I believe, so may be a recurring issue with other UI libraries based on it.

My workaround is to use @click and call capture in a function instead.
