### ISSUE TITLE
Add support for listening to "auxclick" for directive

### ISSUE THREAD

**Issue by Dem1dov1van** [mitjans/nuxt-posthog#54]
Hi! Is it possible to add listener on mouse wheel click for "v-posthog-capture"? For example: i can add @auxclick in vue to detect a "wheel click". But if i use a "v-posthog-capture" this event is ignored

**Comment by mitjans** [comment]
I like the idea of allowing events other than just `'click'`. Would it work for you something like this?

```vue
<MyButton v-posthog-capture:auxclick="'my_event'" />
```

We can pass the name of the event as the argument to the directive (or use `'click'` by default).

**Comment by Dem1dov1van** [comment]
Yeah! It looks great. Really helpfull!

**Comment by mitjans** [comment]
Fixed in the latest version, if you find any problem lmk!
